-- DEPRECATED — do not run.
-- The feedback + suggestions tables and their RLS policies are now part of
-- the single authoritative schema in setup.sql. Run that instead.
--
--   Supabase Dashboard → SQL Editor → paste setup.sql → Run
