-- DEPRECATED — do not run.
-- This file conflicted with setup.sql (it defined `products` without the
-- user_id/store_id ownership columns the app writes to). The authoritative,
-- consolidated, idempotent schema now lives in setup.sql. Run that instead.
--
--   Supabase Dashboard → SQL Editor → paste setup.sql → Run
